services:
  - type: web
    name: nodejs-clean-architecture-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production
